### ISSUE TITLE
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect

### ISSUE THREAD

**Issue by jonaski** [vmactions/freebsd-vm#28]
I'm getting the following error after everything completes.

```
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
rsync: connection unexpectedly closed (276663018 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (96117 bytes received so far) [generator]
rsync error: unexplained error (code 255) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [generator=2.6.9]
```

Full log here: https://github.com/strawberrymusicplayer/strawberry/runs/3208862681

workflow:

```
  build-freebsd:
    name: Build FreeBSD
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build FreeBSD
      id: build-freebsd
      uses: vmactions/freebsd-vm@v0.1.4
      with:
        usesh: true
        mem: 4096
        prepare: pkg install -y git cmake pkgconf gettext-tools boost-libs glib gnutls qt5-core qt5-concurrent qt5-network qt5-sql qt5-dbus qt5-gui qt5-widgets qt5-buildtools qt5-linguisttools qt5-qmake qt5-sqldrivers-sqlite3 qt5-testlib sqlite gstreamer1 gstreamer1-plugins chromaprint protobuf protobuf-c taglib libcdio libmtp gdk-pixbuf2 libgpod fftw3 googletest iconv
        run: |
          sed -i'.original' -e 's/set(INCLUDE_GIT_REVISION ON)/set(INCLUDE_GIT_REVISION OFF)/g' cmake/Version.cmake
          cmake -E make_directory build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build . --config Debug --parallel 4
```
Full file here:

https://github.com/strawberrymusicplayer/strawberry/blob/3a9a8289ba9886f1647582297426b1586c933e8b/.github/workflows/ccpp.yml#L1699

**Comment by dentarg** [comment]
>`ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect`

Maybe this can be of help: https://dentarg.blog/post/186913288147/umac-64-etm

**Comment by acj** [comment]
I've been getting this error intermittently in nightly CI runs. It seems to fail ~20-30% of the time. For example, the [run from two nights ago](https://github.com/rbspy/rbspy/actions/runs/1297182780) succeeded. However, [last night's run](https://github.com/rbspy/rbspy/runs/3779393726) failed with this error:

```
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
rsync: connection unexpectedly closed (114965578 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (106945 bytes received so far) [generator]
rsync error: unexplained error (code 255) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [generator=2.6.9]
Error: The process '/usr/bin/rsync' failed with exit code 255
```

My [workflow](https://github.com/rbspy/rbspy/blob/8af71898016b3b1f0a74ca0e8d746ee972e05150/.github/workflows/ci.yml#L187-L204) is very similar to the one above.

I'm going to try the sshfs alternative sync method and will report back if it's more reliable.

**Comment by gkorland** [comment]
We also started to get this error every other run, is there a solution?
```
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
rsync: connection unexpectedly closed (68987873 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (81665 bytes received so far) [generator]
rsync error: unexplained error (code 255) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [generator=2.6.9]
Error: The process '/usr/bin/rsync' failed with exit code 255
```

**Comment by Neilpang** [comment]
@gkorland 
please try with the latest release.
I never saw this error.

**Comment by gkorland** [comment]
We are using the latest

**Comment by gkorland** [comment]
I'm on the latest release and still getting this error:
```
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect
rsync: connection unexpectedly closed (71193871 bytes received so far) [receiver]
rsync error: error in rsync protocol data stream (code 12) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [receiver=2.6.9]
rsync: connection unexpectedly closed (130324 bytes received so far) [generator]
rsync error: unexplained error (code 255) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/io.c(453) [generator=2.6.9]
Error: The process '/usr/bin/rsync' failed with exit code 255
```
See: https://github.com/RedisJSON/RedisJSON/runs/5110720630?check_suite_focus=true

**Comment by christianparpart** [comment]
I sadly have to line myself up here. It used to work and since quite some time (didn't record the exact date sadly) I started to get the exact same error, too.

**Comment by jonaski** [comment]
I worked around it by wiping the build directory after the build competes.

**Comment by christianparpart** [comment]
> I sadly have to line myself up here. It used to work and since quite some time (didn't record the exact date sadly) I started to get the exact same error, too.

NB: I just realized there's a v0.1.6 out and I was on v0.1.5. I bump it up on my end and now it succeeds. Not sure if that's actually **fixed** or just green by accident. If it's happening again, I'll try your workaround @jonaski, and leave only in build dir whatever is really needed. Thanks for the tip. :)

**Comment by tsuckow** [comment]
I wonder if adding an option to the rsync command might help

`rsync -e 'ssh -o MACs=umac-64-etm@openssh.com'`

**Comment by dentarg** [comment]
@tsuckow Indeed, that was my suggestion with https://github.com/vmactions/freebsd-vm/issues/28#issuecomment-890421968, but maybe many didn't pick up on it

**Comment by Neilpang** [comment]
thanks, I will try it soon.

**Comment by Neilpang** [comment]
fixed, please try the latest release.

**Comment by gruve-p** [comment]
Still not fixed:
https://github.com/Groestlcoin/lightning/actions/runs/3443700100/jobs/5745510315

**Comment by Neilpang** [comment]
@gruve-p   can you please try with `sync: sshfs` ?  maybe that could be better.

**Comment by christianparpart** [comment]
I'm also lately getting many sync failurs. going to try out `sync: sshfs` too, but would be lovely if @gruve-p would be reporting back, too. :)

**Comment by Neilpang** [comment]
@christianparpart     if you don't need to build result files,  you can set `copyback:false` to not copy the files back from the VM to the host machine.   It will help the success rate.

**Comment by gruve-p** [comment]
> @christianparpart if you don't need the build result files, you can set `copyback:false` to not copy the files back from the VM to the host machine. It will help the success rate.

yes this helps the success rate however I need the build result files in my case

**Comment by christianparpart** [comment]
> @christianparpart if you don't need the build result files, you can set `copyback:false` to not copy the files back from the VM to the host machine. It will help the success rate.

that's even better, because in this case I'm only interested in build/test success. Thanks for the tip. :)

**Comment by Neilpang** [comment]
@gruve-p   I understood.  
That was just a tip for users like @christianparpart .

Thanks

**Comment by gruve-p** [comment]
> @gruve-p can you please try with `sync: sshfs` ? maybe that could be better.

Trying now: https://github.com/Groestlcoin/lightning/actions/runs/3444181494/jobs/5746511783
Will keep an eye on it if this is better or same

**Comment by Neilpang** [comment]
@gruve-p   fine,  it seems not better.  please remove `sync: sshfs`.

can you please try `mem: 4096` to increase the memory for the VM?

Thanks

**Comment by gruve-p** [comment]
> @gruve-p fine, it seems not better. please remove `sync: sshfs`.

Done

> can you please try `mem: 4096` to increase the memory for the VM?

Done

https://github.com/Groestlcoin/lightning/actions/runs/3446443764/jobs/5751352398

**Comment by Neilpang** [comment]
@gruve-p   your  mem is 2048.  please try `2096`

**Comment by gruve-p** [comment]
> @gruve-p your mem is 2048. please try `4096`

https://github.com/Groestlcoin/lightning/actions/runs/3450225416/jobs/5758686603
